// source: op.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.deskDelta.CursorOperation');
goog.provide('proto.deskDelta.CursorOperation.CursorOpType');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.deskDelta.IndexBoundary');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.deskDelta.CursorOperation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.deskDelta.CursorOperation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.deskDelta.CursorOperation.displayName = 'proto.deskDelta.CursorOperation';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.deskDelta.CursorOperation.prototype.toObject = function(opt_includeInstance) {
  return proto.deskDelta.CursorOperation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.deskDelta.CursorOperation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.deskDelta.CursorOperation.toObject = function(includeInstance, msg) {
  var f, obj = {
    cursoroptype: jspb.Message.getFieldWithDefault(msg, 6, 0),
    cursorindex: (f = msg.getCursorindex()) && proto.deskDelta.IndexBoundary.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.deskDelta.CursorOperation}
 */
proto.deskDelta.CursorOperation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.deskDelta.CursorOperation;
  return proto.deskDelta.CursorOperation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.deskDelta.CursorOperation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.deskDelta.CursorOperation}
 */
proto.deskDelta.CursorOperation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 6:
      var value = /** @type {!proto.deskDelta.CursorOperation.CursorOpType} */ (reader.readEnum());
      msg.setCursoroptype(value);
      break;
    case 10:
      var value = new proto.deskDelta.IndexBoundary;
      reader.readMessage(value,proto.deskDelta.IndexBoundary.deserializeBinaryFromReader);
      msg.setCursorindex(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.deskDelta.CursorOperation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.deskDelta.CursorOperation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.deskDelta.CursorOperation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.deskDelta.CursorOperation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCursoroptype();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
  f = message.getCursorindex();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.deskDelta.IndexBoundary.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.deskDelta.CursorOperation.CursorOpType = {
  MOVEONERIGHT: 0,
  MOVEONELEFT: 1,
  MOVETOINDEX: 2,
  SELECT: 3
};

/**
 * optional CursorOpType cursorOpType = 6;
 * @return {!proto.deskDelta.CursorOperation.CursorOpType}
 */
proto.deskDelta.CursorOperation.prototype.getCursoroptype = function() {
  return /** @type {!proto.deskDelta.CursorOperation.CursorOpType} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {!proto.deskDelta.CursorOperation.CursorOpType} value
 * @return {!proto.deskDelta.CursorOperation} returns this
 */
proto.deskDelta.CursorOperation.prototype.setCursoroptype = function(value) {
  return jspb.Message.setProto3EnumField(this, 6, value);
};


/**
 * optional IndexBoundary cursorIndex = 10;
 * @return {?proto.deskDelta.IndexBoundary}
 */
proto.deskDelta.CursorOperation.prototype.getCursorindex = function() {
  return /** @type{?proto.deskDelta.IndexBoundary} */ (
    jspb.Message.getWrapperField(this, proto.deskDelta.IndexBoundary, 10));
};


/**
 * @param {?proto.deskDelta.IndexBoundary|undefined} value
 * @return {!proto.deskDelta.CursorOperation} returns this
*/
proto.deskDelta.CursorOperation.prototype.setCursorindex = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.deskDelta.CursorOperation} returns this
 */
proto.deskDelta.CursorOperation.prototype.clearCursorindex = function() {
  return this.setCursorindex(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.deskDelta.CursorOperation.prototype.hasCursorindex = function() {
  return jspb.Message.getField(this, 10) != null;
};


